### ISSUE TITLE
IDEA:  Link albums to immich application.  

### ISSUE THREAD

**Issue by ghzgod** [ad3m3r5/scratch-map#28]
Hello !  Great little app you have here!

If you are not aware of [immich](https://immich.app/), its a neat, selfhosted, very powerful, photos app.  It has a full API and does tons of stuff like geotagging, facial recognition etc.  You could easily use this for tagging locations with albums in your app.  You would get much more adoption too because of the huge user base immich has.  Just another idea.  And finally, thank you for this.  I really love it.  reminds me of the "been" app on ios.

**Comment by ad3m3r5** [comment]
@ghzgod I appreciate the idea! I think it's an interesting concept, as I love Immich, but it probably out of the scope of this project.

While I am trying to add some comfort features, I still want to keep it focused on the idea of a simple scratch-off map.
