### ISSUE TITLE
Provide install instructions without Docker

### ISSUE THREAD

**Issue by natrius** [ad3m3r5/scratch-map#3]
As mentioned in the title :)

**Comment by ad3m3r5** [comment]
In the "Running" section, there are the basic NPM commands to run the project. These should work on any OS where node/npm is available. As for "installing" it as a permanent service, that will very on the OS. Is that what you're looking for?

[Under the ](https://github.com/ad3m3r5/scratch-map/blob/master/README.md#running)

**Comment by ad3m3r5** [comment]
I'm going to close this as there was documentation on the subject, and PM2 has now been referenced as another option.
