### ISSUE TITLE
[BUG] Strange Characters in https://

### ISSUE THREAD

**Issue by mariushosting** [ad3m3r5/scratch-map#30]
https:**//** links give back random characters for //

![savedlink bug](https://github.com/user-attachments/assets/fa0276f8-ae45-414f-84d2-9c018887ada5)

**Comment by ad3m3r5** [comment]
Thanks for catching this! In my dev branch I removed that column of the table, so I didn't catch it. I'll have to change the way it renders that. I'll try to get it fixed soon

**Comment by ad3m3r5** [comment]
This should be fixed in the latest release, 1.2.3, and a docker build should be completed soon. Feel free to re-open if the issue persists for some reason.

Thanks again!
